# Generated by Django 3.2.13 on 2022-10-25 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='users',
            new_name='like_users',
        ),
    ]
